version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=172.31.18.12 # Use this to connect to localhost from the container
      - DB_USER=root # The MySQL user you set up
      - DB_PASSWORD=password # The MySQL user's password
      - DB_NAME=rsj_be # The database name
      - DB_PORT=3309
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
